name: Attestation

on:

  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

jobs:

  artifact:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building..."
          echo "Artifact" > artifact.txt

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact.txt

  attestation:

    runs-on: ubuntu-latest
    needs: artifact

    steps:

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: downloaded-artifact

      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'downloaded-artifact/artifact.txt'