name: Hello World

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: hello-world
        run: echo "hello world"
      - name: Set output example
        id: step1
        run: echo "::set-output name=myOutput::Hello, World!"
      - name: Display output
        run: echo "The output is ${{ steps.step1.outputs.myOutput }}"
