name: Hello World

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      group: capgemini
      labels: ubuntu-latest

    steps:
      - name: hello-world
        run: echo "hello world"
