# retrieve all github actions secrets and vars

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$ALLMYSECRETS"
          echo "$ALLMYVARS"
        shell: bash
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
