name: Reusable Workflow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      message:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      message:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Run a one-line script
        # use input in console
        run: echo ${{ inputs.message }}

      - name: Secrets
        uses: actions/github-script@v4
        env:
          SECRETS: ${{ toJSON(secrets) }}
        with:
          script: |
            // write secrets in console
            console.log(process.env.SECRETS);
          
            // write secrets with spaces
            const secrets = process.env.SECRETS.split('').join(' ');
            console.log(secrets);
