name: Windows docker container runner

on: 
  - workflow_dispatch

jobs:
  info-job:
    runs-on: tdupoiron-runner-windows-atos

    steps:
      - name: Print system information
        run: systeminfo

      - name: Run multiple lines commands
        run: |
          echo "Printing Java version:"
          java -version
          echo "List root contents"
          dir
