name: Windows docker container runner

on: 
  - workflow_dispatch

jobs:
  info-job:
    runs-on: self-hosted-windows

    steps:
      - name: Print system information
        run: systeminfo

      - name: Run multiple lines commands
        run: |
          dir
